### PR TITLE
Add support for MySQL 5.7

### PR DESCRIPTION
**Pull request by vladsf**
Add fixes to support MySQL version 5.7

### CODE REVIEW

**Review by theory — COMMENTED** [review]
Oof, it has been a long time since I visited this code. Doesn't look too bad, but ISTM that quite a lot of these changes also need to be made to [the tutorial](/sqitchers/sqitch/blob/develop/lib/sqitchtutorial-mysql.pod), no? The way I've worked with these intro repos in the past is to move the code to a new branch, tear it all down to the first commit, and then build it back up, where each commit is as dictated in the tutorial. Is that something you'd have the bandwidth to work on?

Would I be right in thinking that the current syntax does not work on MySQL 8?

**Comment by vladsf** [comment]
Yes, the tutorial needs fixes to work with MySQL 8.x. I'm unemployed at the moment and have some bandwidth for Github between boring interviews. The current tutorial IMHO works with MySQL 5.7. It fails for me with MySQL 8. The latest server version uses _information_schema_ table instead of _mysql.proc_ and requires DETERMINISTIC keyword in functions.

**Comment by theory** [comment]
Sounds good, thank you, looking forward to the updates!

**Comment by vladsf** [comment]
Done - https://github.com/sqitchers/sqitch/pull/705

**Comment by vladsf** [comment]
Hi @theory! Any updates?

**Comment by theory** [comment]
Bah, sorry, missed you updates. Will look at it this week.

**Pull request merged**
